const mockFarmsData = [
    {
        farmId: 1,
        farmName: "Green Valley",
        owner: "Alice N.",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Nyagatare",
        sector: "Rwempasha",
        cell: "Rugarama",
        village: "Kigarama",
        moisture: 43,
        pumpStatus: "ON",
        waterUsedToday: 1200.5,
        avgEfficiency: 85,
        lastIrrigated: "2025-07-26T06:30:00Z",
        farmSize: 2.1,
    },
    {
        farmId: 2,
        farmName: "Sunrise Farm",
        owner: "Emmanuel M.",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Nyagatare",
        sector: "Tabagwe",
        cell: "Gakirage",
        village: "Kabeza",
        moisture: 28,
        pumpStatus: "OFF",
        waterUsedToday: 0,
        avgEfficiency: 40,
        lastIrrigated: "2025-07-25T19:15:00Z",
        farmSize: 1.6,
    },
    {
        farmId: 3,
        farmName: "Hope Harvest",
        owner: "Marie Claire",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Kayonza",
        sector: "Rukara",
        cell: "Nyagatovu",
        village: "Buhabwa",
        moisture: 52,
        pumpStatus: "ON",
        waterUsedToday: 1890.75,
        avgEfficiency: 92,
        lastIrrigated: "2025-07-26T05:10:00Z",
        farmSize: 3.5,
    },
    {
        farmId: 4,
        farmName: "Rwema Produce",
        owner: "Jean Bosco",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Kayonza",
        sector: "Murundi",
        cell: "Kabura",
        village: "Gasave",
        moisture: 18,
        pumpStatus: "OFF",
        waterUsedToday: 0,
        avgEfficiency: 31,
        lastIrrigated: "2025-07-24T17:45:00Z",
        farmSize: 2.7,
    },
    {
        farmId: 5,
        farmName: "Karama Crops",
        owner: "John Paul",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Bugesera",
        sector: "Ruhuha",
        cell: "Karama",
        village: "Gikombe",
        moisture: 40,
        pumpStatus: "ON",
        waterUsedToday: 1333.1,
        avgEfficiency: 82,
        lastIrrigated: "2025-07-26T07:45:00Z",
        farmSize: 2.0,
    },
    {
        farmId: 6,
        farmName: "Akagera Greens",
        owner: "David R.",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Ngoma",
        sector: "Zaza",
        cell: "Kirehe",
        village: "Nyabikokora",
        moisture: 59,
        pumpStatus: "ON",
        waterUsedToday: 1150.3,
        avgEfficiency: 79,
        lastIrrigated: "2025-07-26T08:20:00Z",
        farmSize: 3.9,
    },
    {
        farmId: 7,
        farmName: "Nyiramugisha Estate",
        owner: "Sarah K.",
        province: "Western Province",
        zone: "Western",
        district: "Karongi",
        sector: "Bwishyura",
        cell: "Kibuye",
        village: "Mubuga",
        moisture: 67,
        pumpStatus: "ON",
        waterUsedToday: 980.6,
        avgEfficiency: 87,
        lastIrrigated: "2025-07-26T07:55:00Z",
        farmSize: 1.2,
    },
    {
        farmId: 8,
        farmName: "Volcano Agri",
        owner: "Eric N.",
        province: "Northern Province",
        zone: "Northern",
        district: "Musanze",
        sector: "Muhoza",
        cell: "Ruhengeri",
        village: "Gakoro",
        moisture: 33,
        pumpStatus: "OFF",
        waterUsedToday: 0,
        avgEfficiency: 41,
        lastIrrigated: "2025-07-23T12:45:00Z",
        farmSize: 2.5,
    },
    {
        farmId: 9,
        farmName: "Umurima Mwiza",
        owner: "Angela Uwase",
        province: "Southern Province",
        zone: "Southern",
        district: "Huye",
        sector: "Tumba",
        cell: "Ruhashya",
        village: "Kanyinya",
        moisture: 47,
        pumpStatus: "ON",
        waterUsedToday: 1600.25,
        avgEfficiency: 89,
        lastIrrigated: "2025-07-26T09:20:00Z",
        farmSize: 1.8,
    },
    {
        farmId: 10,
        farmName: "Kigali Agro Farm",
        owner: "Claude R.",
        province: "Kigali City",
        zone: "Kigali",
        district: "Gasabo",
        sector: "Kimironko",
        cell: "Bibare",
        village: "Gihogwe",
        moisture: 35,
        pumpStatus: "ON",
        waterUsedToday: 1220.4,
        avgEfficiency: 75,
        lastIrrigated: "2025-07-26T10:00:00Z",
        farmSize: 2.2,
    },
    {
        farmId: 11,
        farmName: "Green Valley",
        owner: "Alice N.",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Nyagatare",
        sector: "Rwempasha",
        cell: "Rugarama",
        village: "Kigarama",
        moisture: 43,
        pumpStatus: "ON",
        waterUsedToday: 1200.5,
        avgEfficiency: 85,
        lastIrrigated: "2025-07-26T06:30:00Z",
        farmSize: 2.1,
    },
    {
        farmId: 12,
        farmName: "Sunrise Farm",
        owner: "Emmanuel M.",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Nyagatare",
        sector: "Tabagwe",
        cell: "Gakirage",
        village: "Kabeza",
        moisture: 28,
        pumpStatus: "OFF",
        waterUsedToday: 0,
        avgEfficiency: 40,
        lastIrrigated: "2025-07-25T19:15:00Z",
        farmSize: 1.6,
    },
    {
        farmId: 13,
        farmName: "Hope Harvest",
        owner: "Marie Claire",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Kayonza",
        sector: "Rukara",
        cell: "Nyagatovu",
        village: "Buhabwa",
        moisture: 52,
        pumpStatus: "ON",
        waterUsedToday: 1890.75,
        avgEfficiency: 92,
        lastIrrigated: "2025-07-26T05:10:00Z",
        farmSize: 3.5,
    },
    {
        farmId: 14,
        farmName: "Rwema Produce",
        owner: "Jean Bosco",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Kayonza",
        sector: "Murundi",
        cell: "Kabura",
        village: "Gasave",
        moisture: 18,
        pumpStatus: "OFF",
        waterUsedToday: 0,
        avgEfficiency: 31,
        lastIrrigated: "2025-07-24T17:45:00Z",
        farmSize: 2.7,
    },
    {
        farmId: 15,
        farmName: "Karama Crops",
        owner: "John Paul",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Bugesera",
        sector: "Ruhuha",
        cell: "Karama",
        village: "Gikombe",
        moisture: 40,
        pumpStatus: "ON",
        waterUsedToday: 1333.1,
        avgEfficiency: 82,
        lastIrrigated: "2025-07-26T07:45:00Z",
        farmSize: 2.0,
    },
    {
        farmId: 16,
        farmName: "Akagera Greens",
        owner: "David R.",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Ngoma",
        sector: "Zaza",
        cell: "Kirehe",
        village: "Nyabikokora",
        moisture: 59,
        pumpStatus: "ON",
        waterUsedToday: 1150.3,
        avgEfficiency: 79,
        lastIrrigated: "2025-07-26T08:20:00Z",
        farmSize: 3.9,
    },
    {
        farmId: 17,
        farmName: "Golden Fields",
        owner: "Ange Uwase",
        province: "Southern Province",
        zone: "Southern",
        district: "Nyanza",
        sector: "Muyira",
        cell: "Cell-3",
        village: "Village-3",
        moisture: 44,
        pumpStatus: "OFF",
        waterUsedToday: 0.0,
        avgEfficiency: 66,
        lastIrrigated: "2025-07-25T22:58:10.177310",
        farmSize: 1.8,
    },
    {
        farmId: 18,
        farmName: "Blue Harvest",
        owner: "Pascaline Nyirahabimana",
        province: "Kigali City",
        zone: "Kigali",
        district: "Nyarugenge",
        sector: "Gitega",
        cell: "Cell-1",
        village: "Village-6",
        moisture: 23,
        pumpStatus: "ON",
        waterUsedToday: 1459.98,
        avgEfficiency: 80,
        lastIrrigated: "2025-07-25T12:58:10.177340",
        farmSize: 2.4,
    },
    {
        farmId: 19,
        farmName: "Green Hills Farm",
        owner: "Eric Ndahiro",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Nyagatare",
        sector: "Karangazi",
        cell: "Cell-2",
        village: "Village-10",
        moisture: 60,
        pumpStatus: "OFF",
        waterUsedToday: 0.0,
        avgEfficiency: 55,
        lastIrrigated: "2025-07-24T17:58:10.177370",
        farmSize: 3.1,
    },
    {
        farmId: 20,
        farmName: "Ubutaka Nziza",
        owner: "Claudine Mukamana",
        province: "Northern Province",
        zone: "Northern",
        district: "Rulindo",
        sector: "Rusiga",
        cell: "Cell-1",
        village: "Village-7",
        moisture: 38,
        pumpStatus: "OFF",
        waterUsedToday: 0.0,
        avgEfficiency: 50,
        lastIrrigated: "2025-07-23T18:58:10.177390",
        farmSize: 1.2,
    },
    {
        farmId: 21,
        farmName: "IrrigoTech Farm",
        owner: "Jean Claude Rwema",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Bugesera",
        sector: "Juru",
        cell: "Cell-4",
        village: "Village-5",
        moisture: 47,
        pumpStatus: "ON",
        waterUsedToday: 1698.2,
        avgEfficiency: 91,
        lastIrrigated: "2025-07-26T03:12:00.000Z",
        farmSize: 3.8,
    },
    {
        farmId: 22,
        farmName: "Harvest Bridge",
        owner: "Felicite Uwitonze",
        province: "Western Province",
        zone: "Western",
        district: "Karongi",
        sector: "Bwishyura",
        cell: "Cell-2",
        village: "Village-2",
        moisture: 33,
        pumpStatus: "OFF",
        waterUsedToday: 0.0,
        avgEfficiency: 60,
        lastIrrigated: "2025-07-24T09:20:00.000Z",
        farmSize: 2.0,
    },
    {
        farmId: 23,
        farmName: "AgroTrack Plot",
        owner: "Patrick Mugabo",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Ngoma",
        sector: "Zaza",
        cell: "Cell-3",
        village: "Village-1",
        moisture: 58,
        pumpStatus: "ON",
        waterUsedToday: 1225.4,
        avgEfficiency: 87,
        lastIrrigated: "2025-07-26T04:50:00.000Z",
        farmSize: 4.2,
    },
    {
        farmId: 24,
        farmName: "EcoFarm Rwanda",
        owner: "Sylvia Ingabire",
        province: "Kigali City",
        zone: "Kigali",
        district: "Gasabo",
        sector: "Remera",
        cell: "Cell-5",
        village: "Village-7",
        moisture: 41,
        pumpStatus: "OFF",
        waterUsedToday: 0.0,
        avgEfficiency: 48,
        lastIrrigated: "2025-07-25T16:42:00.000Z",
        farmSize: 0.9,
    },
    {
        farmId: 25,
        farmName: "Inka Garden",
        owner: "Alphonse Nizeyimana",
        province: "Southern Province",
        zone: "Southern",
        district: "Huye",
        sector: "Ngoma",
        cell: "Cell-2",
        village: "Village-6",
        moisture: 63,
        pumpStatus: "ON",
        waterUsedToday: 1380.7,
        avgEfficiency: 78,
        lastIrrigated: "2025-07-26T06:10:00.000Z",
        farmSize: 2.5,
    },
    {
        farmId: 26,
        farmName: "Ishyamba Farm",
        owner: "Yvette Umulisa",
        province: "Northern Province",
        zone: "Northern",
        district: "Musanze",
        sector: "Muhoza",
        cell: "Cell-3",
        village: "Village-4",
        moisture: 50,
        pumpStatus: "OFF",
        waterUsedToday: 0.0,
        avgEfficiency: 64,
        lastIrrigated: "2025-07-24T13:15:00.000Z",
        farmSize: 3.6,
    },
    {
        farmId: 27,
        farmName: "Kora Neza Farm",
        owner: "Celestin Habimana",
        province: "Western Province",
        zone: "Western",
        district: "Rubavu",
        sector: "Nyamyumba",
        cell: "Cell-1",
        village: "Village-3",
        moisture: 27,
        pumpStatus: "ON",
        waterUsedToday: 1510.9,
        avgEfficiency: 83,
        lastIrrigated: "2025-07-26T08:00:00.000Z",
        farmSize: 2.9,
    },
    {
        farmId: 28,
        farmName: "TeraLink Fields",
        owner: "Josiane Murekatete",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Kirehe",
        sector: "Kigarama",
        cell: "Cell-2",
        village: "Village-8",
        moisture: 39,
        pumpStatus: "OFF",
        waterUsedToday: 0.0,
        avgEfficiency: 46,
        lastIrrigated: "2025-07-25T14:40:00.000Z",
        farmSize: 1.4,
    },
    {
        farmId: 29,
        farmName: "Umucyo Agro",
        owner: "Theogene Rutikanga",
        province: "Southern Province",
        zone: "Southern",
        district: "Nyanza",
        sector: "Busasamana",
        cell: "Cell-3",
        village: "Village-9",
        moisture: 55,
        pumpStatus: "ON",
        waterUsedToday: 1295.6,
        avgEfficiency: 88,
        lastIrrigated: "2025-07-26T07:35:00.000Z",
        farmSize: 3.0,
    },
    {
        farmId: 30,
        farmName: "Intego Farmstead",
        owner: "Marie Louise Umwali",
        province: "Eastern Province",
        zone: "Eastern",
        district: "Rwamagana",
        sector: "Nyakariro",
        cell: "Cell-4",
        village: "Village-10",
        moisture: 46,
        pumpStatus: "ON",
        waterUsedToday: 1342.3,
        avgEfficiency: 86,
        lastIrrigated: "2025-07-26T09:05:00.000Z",
        farmSize: 2.6,
    }
];
export default mockFarmsData;